contact/index.html
jobs/index.html
jobs/ux-designer.md

company address is now more specific + info on the train is included

Adapt job ad

---

jobs/golang-developer.md
jobs/ux-designer.md
technology/index.md

this is still a draft and should properly be done by @dhaavi - hence it is only accessible by the direct link

Feature golang dev job ad

---

_config.yml
_data/community_hub.yml
_layouts/podcast.html
_podcasts/2019-09-13-how-to-fund-a-privacy-oriented-start-up.md
_podcasts/2019-09-19-decisions-that-shift-a-company.md
podcast.html
podcast.xml

Things to improve:
- link to rss
- format podcast index, add some meta info + description

Podcast v2

---

_includes/header.html
_sass/_header.scss

- removed uppercase markup wording
- exchanged html with scss styling
- removed whitespace
- removed unused code

Removed uppercase wording and added styles for it. 

---

_config.yml
_includes/new/footer.html
_sass/_post.scss
podcast/index.html

This pull adds #40 and also iTunes to the footer.

Podcast iTunes & RSS links

---

_includes/footer.html
_sass/_global.scss
index.html
portmaster/index.html
spn/index.html

went through the texts and its technical correctness with Daniel, which counts as an approval

Spn description texts

---

_includes/header.html
_layouts/page_container.html
_layouts/podcast.html
_layouts/post.html
_layouts/video.html
_sass/_page_container.scss
about/index.html
blog/index.html
index.html
ownership/index.html
podcast/index.html
portmaster/index.html
spn/index.html
team/index.html
video/index.html

tackles the most crucial styling bugs on mobile, should work for now. We can attempt some more long-term solutions lateron
Reviewed on my phone locally

Fix mobile optimization

---

ownership/index.html

adds a card to the influences section.
@LukeSeers please check the wording & the order of the cards. Thought it fitted best as Nr. 3, what are your thoughts?

Kickstarter Card in influences

---

_posts/2020-06-26-progress-update.md

reviewed by @Raphty internally

Add first Progress Update in blog form

---

_data/backlog.yml
_data/next.yml
_posts/2020-08-31-progress-update-august.html
next/index.html

@Raphty, please review all texts.
@dhaavi, please review all texts AND create a text for the Portscan Detection.
If anything is incorrect, please adapt the texts and when everything is ready merge it on the 31st of August or early September.
@Raphty please promote the new post on reddit and on Twitter.
@dhaavi, when running locally, you must change the date to the past or present for the page to show up.

Progress Update Blog Post August

---

_posts/2020-09-02-ama-we-want-your-feedback.md

This PR implements the feedback from https://github.com/safing/web/pull/96 that was left out because of a misunderstanding. This PR goes a bit further with that feedback and has already been approved by Raphael.

Revamp blog post and implement feedback

---

_data/next.yml
_posts/2020-12-03-progress-update-november.html
ownership/index.html

- includes the new numbers for the ownership page

Progress update november

---

_data/next.yml
_includes/project_tablecard.html
_posts/2021-01-04-progress-update-december.html
_sass/_global.scss

ready for take-off. If you want to change things before publishing ping Daniel and he'll be able to do so.
Other than that, this is scheduled for publishing on 4th of January

Progress update december

---

_data/backlog.yml
_data/next.yml
_posts/2021-01-04-progress-update-december.html
_posts/2021-02-04-progress-update-january.html
backlog/index.html
next/index.html

- brings next page up to speed
- adds new documentation cards to the next & backlog page
- blog itself for January is still missing, but would be nice if you could already review the new cards @dhaavi

Progress Update January

---

portmaster/index.html

this way we can link to specific features from outside. This will first be used in the new Portmaster README

Anchor feature divs with ids

---

_layouts/page_container.html
privacy/index.md
terms/index.md

This now only contains the legal information

Update Privacy Policy

---

_data/backlog.yml

had it on our radar, but through input from https://www.youtube.com/watch?v=GusN5EcrlCU it was time to put this officially into the backlog.
approved by @Raphty

Add "Ditch Electron" task to backlog

---

_publications/2021-04-06-we-were-on-tv.md

reviewed by Daniel and Raphael in a meeting

Write 2M2M blog

---

_data/next.yml
_publications/2021-04-08-progress-update-march.md
backlog/index.html
next/index.html

Progress Update Blog march

---

_config.yml
blog.xml
docker-compose.yml
feed.xml

please make an after the fact review

Fix RSS feed

---

_data/backlog.yml
_data/next.yml
_publications/2021-06-02-progress-update-may.md
backlog/index.html
next/index.html

@Raphty, if you want to fix typos / text, or remove parts etc, please ask @ppacher for help

Progress update may

---

_config.yml
_data/backlog.yml
_data/next.yml
_publications/2021-11-05-progress-update-october.md

Progress Update October

---

portmaster/index.html
spn/index.html

- update download section
- link buttons to docs instead of direct installers, so ppl can read important notes
- link to installer checksums
- SPN page
- add margin to FAQ bottom
- correctly switch plans

Update download buttons

---

_includes/footer.html

update repository url for SPN source code

---

pricing/index.html

What kind of change does this PR introduce?
The pricing feature comparison tooltips have an outdated text and should be replaced with "planned".
- [] Documentation content changes
Please check if your PR fulfills the following requirements:
The pricing feature comparison tooltips display "coming 2024".

Update pricing tooltips for planned features

---

_includes/footer.html

What kind of change does this PR introduce?
The home page newsletter form is removed.
- [] Documentation content changes
Please check if your PR fulfills the following requirements:
A newsletter form is displayed in the home page.

task: Remove newsletter from home page
